# Generated by Django 4.0.4 on 2022-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithms',
            name='space_complexity',
            field=models.CharField(default='O(1)', max_length=100),
        ),
        migrations.AddField(
            model_name='algorithms',
            name='time_complexity',
            field=models.CharField(default='O(n)', max_length=100),
        ),
    ]
