# Generated by Django 4.0.4 on 2022-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_algorithms_space_complexity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
