# Generated by Django 4.0.4 on 2022-04-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_algorithmtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithms',
            name='algorithm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='algorithms.algorithmtype'),
        ),
    ]
